export const projectsData = [
  {
    id: 1,
    name: "Appointment Day",
    description: "Book and manage appointments",
    date: "2023-06",
    demoLink: "https://ecotracker.example.com",
  },
  {
    id: 2,
    name: "Fee Transfer App",
    description: "Pay tuition with student code",
    date: "2024-05",
    demoLink: "https://artgalleryonline.example.com",
  },
  {
    id: 3,
    name: "Store management system",
    description: "Provides Point of Sale",
    date: "2023-11",
    demoLink: "https://budgetplanner.example.com",
  },
  {
    id: 4,
    name: "GETTECH",
    description: "Trading and managing technology products",
    date: "2024-01",
    demoLink: "https://healthbeat.example.com",
  },
  {
    id: 5,
    name: "Twitter Clone",
    description: "Clone the main functions of twitter",
    date: "2024-06",
    demoLink: "https://recipefinder.example.com",
  },
  {
    id: 6,
    name: "Komo-Portfolio",
    description: "My portfolio website",
    date: "2024-07",
    demoLink: "https://journeylogger.example.com",
  },
];

export const BtnList = [
  {
    id: 1,
    label: "Home",
    link: "/",
    icon: "home",
    newTab: false,
  },
  {
    id: 2,
    label: "About",
    link: "/about",
    icon: "about",
    newTab: false,
  },
  {
    id: 3,
    label: "Projects",
    link: "/projects",
    icon: "projects",
    newTab: false,
  },
  {
    id: 4,
    label: "Contact",
    link: "/contact",
    icon: "contact",
    newTab: false,
  },
  {
    id: 5,
    label: "Github",
    link: "https://github.com/HTTDuong",
    icon: "github",
    newTab: true,
  },
  {
    id: 6,
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/httduong/",
    icon: "linkedin",
    newTab: true,
  },
  {
    id: 7,
    label: "X",
    link: "",
    icon: "twitter",
    newTab: true,
  },
  {
    id: 8,
    label: "Resume",
    link: "/HaThiThuyDuong_Resume.pdf",
    icon: "resume",
    newTab: true,
  },
];
